version: '3'
services:
  application:
    platform: linux/amd64
    image: yangxiaodong/apijson:0.0.1-beta.5
    environment:
      - ADMIN_HOST=admin
      - REDIS_HOST=redis1
      - REDIS_PORT=6379
    ports:
      - "8888:8080"
    restart: always
    volumes:
      - ./bootstrap/target:/usr/project/bootstrap
    command: ['java', '-jar', '/usr/src/app/app.jar']

